name: zsdk
description: A Flutter plugin for printers using Zebra Link OS, to allow ZPL and PDF priting over TCP/IP connections.
version: 3.2.0+3
homepage: https://github.com/luis901101/zsdk
issue_tracker: https://github.com/luis901101/zsdk/issues
topics:
  - zebra
  - thermal
  - ticket
  - printer

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.flutter.zsdk
        pluginClass: ZsdkPlugin
      ios:
        pluginClass: ZsdkPlugin
